#Embedded file name: ACEStream\Core\BitTornado\BT1\MessageID.pyo
protocol_name = 'BitTorrent protocol'
option_pattern = '\x00\x00\x00\x00\x000\x00\x00'
CHOKE = chr(0)
UNCHOKE = chr(1)
INTERESTED = chr(2)
NOT_INTERESTED = chr(3)
HAVE = chr(4)
BITFIELD = chr(5)
REQUEST = chr(6)
PIECE = chr(7)
CANCEL = chr(8)
PORT = chr(9)
EXTEND = chr(20)
CHALLENGE = chr(253)
RESPONSE1 = chr(252)
RESPONSE2 = chr(251)
HASHPIECE = chr(250)
BUDDYCAST = chr(249)
GET_METADATA = chr(248)
METADATA = chr(247)
DIALBACK_REQUEST = chr(244)
DIALBACK_REPLY = chr(243)
ASK_FOR_HELP = chr(246)
STOP_HELPING = chr(245)
REQUEST_PIECES = chr(242)
CANCEL_PIECE = chr(241)
JOIN_HELPERS = chr(224)
RESIGN_AS_HELPER = chr(223)
DROPPED_PIECE = chr(222)
PROXY_HAVE = chr(221)
PROXY_UNHAVE = chr(220)
KEEP_ALIVE = chr(240)
SOCIAL_OVERLAP = chr(239)
QUERY = chr(238)
QUERY_REPLY = chr(237)
BARTERCAST = chr(236)
G2G_PIECE_XFER = chr(235)
FRIENDSHIP = chr(234)
CRAWLER_REQUEST = chr(232)
CRAWLER_REPLY = chr(231)
VOTECAST = chr(226)
CHANNELCAST = chr(225)
GET_SUBS = chr(230)
SUBS = chr(229)
EXTEND_MSG_INVALIDATE_ID = chr(219)
CS_CHALLENGE_A = chr(227)
CS_CHALLENGE_B = chr(228)
CS_POA_EXCHANGE_A = chr(229)
CS_POA_EXCHANGE_B = chr(230)
CRAWLER_DATABASE_QUERY = chr(1)
CRAWLER_SEEDINGSTATS_QUERY = chr(2)
CRAWLER_NATCHECK = chr(3)
CRAWLER_FRIENDSHIP_STATS = chr(4)
CRAWLER_NATTRAVERSAL = chr(5)
CRAWLER_VIDEOPLAYBACK_INFO_QUERY = chr(6)
CRAWLER_VIDEOPLAYBACK_EVENT_QUERY = chr(7)
CRAWLER_REPEX_QUERY = chr(8)
CRAWLER_PUNCTURE_QUERY = chr(9)
CRAWLER_CHANNEL_QUERY = chr(10)
CRAWLER_USEREVENTLOG_QUERY = chr(11)
PermIDMessages = [CHALLENGE, RESPONSE1, RESPONSE2]
BuddyCastMessages = [CHANNELCAST,
 VOTECAST,
 BARTERCAST,
 BUDDYCAST,
 KEEP_ALIVE]
MetadataMessages = [GET_METADATA, METADATA]
DialbackMessages = [DIALBACK_REQUEST, DIALBACK_REPLY]
HelpCoordinatorMessages = [ASK_FOR_HELP,
 STOP_HELPING,
 REQUEST_PIECES,
 CANCEL_PIECE]
HelpHelperMessages = [JOIN_HELPERS,
 RESIGN_AS_HELPER,
 DROPPED_PIECE,
 PROXY_HAVE,
 PROXY_UNHAVE]
SocialNetworkMessages = [SOCIAL_OVERLAP]
RemoteQueryMessages = [QUERY, QUERY_REPLY]
VoDMessages = [G2G_PIECE_XFER]
FriendshipMessages = [FRIENDSHIP]
CrawlerMessages = [CRAWLER_REQUEST, CRAWLER_REPLY]
SubtitleMessages = [GET_SUBS, SUBS]
OverlaySwarmMessages = PermIDMessages + BuddyCastMessages + MetadataMessages + HelpCoordinatorMessages + HelpHelperMessages + SocialNetworkMessages + RemoteQueryMessages + CrawlerMessages
message_map = {CHOKE: 'CHOKE',
 UNCHOKE: 'UNCHOKE',
 INTERESTED: 'INTEREST',
 NOT_INTERESTED: 'NOT_INTEREST',
 HAVE: 'HAVE',
 BITFIELD: 'BITFIELD',
 REQUEST: 'REQUEST',
 CANCEL: 'CANCEL',
 PIECE: 'PIECE',
 PORT: 'PORT',
 EXTEND: 'EXTEND',
 CHALLENGE: 'CHALLENGE',
 RESPONSE1: 'RESPONSE1',
 RESPONSE2: 'RESPONSE2',
 HASHPIECE: 'HASHPIECE',
 BUDDYCAST: 'BUDDYCAST',
 GET_METADATA: 'GET_METADATA',
 METADATA: 'METADATA',
 ASK_FOR_HELP: 'ASK_FOR_HELP',
 STOP_HELPING: 'STOP_HELPING',
 REQUEST_PIECES: 'REQUEST_PIECES',
 CANCEL_PIECE: 'CANCEL_PIECE',
 JOIN_HELPERS: 'JOIN_HELPERS',
 RESIGN_AS_HELPER: 'RESIGN_AS_HELPER',
 DROPPED_PIECE: 'DROPPED_PIECE',
 PROXY_HAVE: 'PROXY_HAVE',
 PROXY_UNHAVE: 'PROXY_UNHAVE',
 DIALBACK_REQUEST: 'DIALBACK_REQUEST',
 DIALBACK_REPLY: 'DIALBACK_REPLY',
 KEEP_ALIVE: 'KEEP_ALIVE',
 SOCIAL_OVERLAP: 'SOCIAL_OVERLAP',
 QUERY: 'QUERY',
 QUERY_REPLY: 'QUERY_REPLY',
 VOTECAST: 'VOTECAST',
 BARTERCAST: 'BARTERCAST',
 G2G_PIECE_XFER: 'G2G_PIECE_XFER',
 FRIENDSHIP: 'FRIENDSHIP',
 VOTECAST: 'VOTECAST',
 CHANNELCAST: 'CHANNELCAST',
 CRAWLER_REQUEST: 'CRAWLER_REQUEST',
 CRAWLER_REQUEST + CRAWLER_DATABASE_QUERY: 'CRAWLER_DATABASE_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_SEEDINGSTATS_QUERY: 'CRAWLER_SEEDINGSTATS_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_NATCHECK: 'CRAWLER_NATCHECK_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_NATTRAVERSAL: 'CRAWLER_NATTRAVERSAL_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_FRIENDSHIP_STATS: 'CRAWLER_FRIENDSHIP_STATS_REQUEST',
 CRAWLER_REQUEST + CRAWLER_VIDEOPLAYBACK_INFO_QUERY: 'CRAWLER_VIDEOPLAYBACK_INFO_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_VIDEOPLAYBACK_EVENT_QUERY: 'CRAWLER_VIDEOPLAYBACK_EVENT_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_REPEX_QUERY: 'CRAWLER_REPEX_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_PUNCTURE_QUERY: 'CRAWLER_PUNCTURE_QUERY_REQUEST',
 CRAWLER_REQUEST + CRAWLER_CHANNEL_QUERY: 'CRAWLER_CHANNEL_QUERY_REQUEST',
 CRAWLER_REPLY: 'CRAWLER_REPLY',
 CRAWLER_REPLY + CRAWLER_DATABASE_QUERY: 'CRAWLER_DATABASE_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_SEEDINGSTATS_QUERY: 'CRAWLER_SEEDINGSTATS_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_NATCHECK: 'CRAWLER_NATCHECK_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_NATTRAVERSAL: 'CRAWLER_NATTRAVERSAL_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_FRIENDSHIP_STATS: 'CRAWLER_FRIENDSHIP_STATS',
 CRAWLER_REPLY + CRAWLER_FRIENDSHIP_STATS: 'CRAWLER_FRIENDSHIP_STATS_REPLY',
 CRAWLER_REPLY + CRAWLER_VIDEOPLAYBACK_INFO_QUERY: 'CRAWLER_VIDEOPLAYBACK_INFO_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_VIDEOPLAYBACK_EVENT_QUERY: 'CRAWLER_VIDEOPLAYBACK_EVENT_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_REPEX_QUERY: 'CRAWLER_REPEX_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_PUNCTURE_QUERY: 'CRAWLER_PUNCTURE_QUERY_REPLY',
 CRAWLER_REPLY + CRAWLER_CHANNEL_QUERY: 'CRAWLER_CHANNEL_QUERY_REPLY'}

def getMessageName(s):
    if s in message_map:
        return message_map[s]
    else:
        return 'Unknown_MessageID_' + '_'.join([ str(ord(c)) for c in s ])
