#Embedded file name: ACEStream\Video\defs.pyo
PLAYBACKMODE_INTERNAL = 0
PLAYBACKMODE_EXTERNAL_DEFAULT = 1
PLAYBACKMODE_EXTERNAL_MIME = 2
OTHERTORRENTS_STOP_RESTART = 0
OTHERTORRENTS_STOP = 1
OTHERTORRENTS_CONTINUE = 2
MEDIASTATE_PLAYING = 1
MEDIASTATE_PAUSED = 2
MEDIASTATE_STOPPED = 3
BGP_STATE_IDLE = 0
BGP_STATE_PREBUFFERING = 1
BGP_STATE_DOWNLOADING = 2
BGP_STATE_BUFFERING = 3
BGP_STATE_COMPLETED = 4
BGP_STATE_HASHCHECKING = 5
BGP_STATE_ERROR = 6
