#Embedded file name: ACEStream\Plugin\defs.pyo
URLPATH_CONTENT_PREFIX = '/content'
URLPATH_TORRENT_POSTFIX = '.tstream'
URLPATH_NSMETA_POSTFIX = '.xml'
URLPATH_THUMBNAIL_POSTFIX = '/thumbnail'
URLPATH_HITS_PREFIX = '/hits'
URLPATH_SEARCH_PREFIX = '/search'
URLPATH_WEBIF_PREFIX = '/webui'
HITS_TIMEOUT = 1800.0
